<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $url
     * @return null|Category|object
     */
    public function findByUrl($url)
    {
        return $this->findOneBy([
            'url' => $url
        ]);
    }

    /**
     * @param Category $category
     * @return Category
     */
    public function save(Category $category)
    {
        $this->_em->persist($category);
        $this->_em->flush();

        return $category;
    }
}
