<?php

namespace AppBundle\Repository;

/**
 * ClampTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClampTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
