<?php

namespace AppBundle\Repository;

/**
 * ConstructionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstructionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
