<?php

namespace App\Repository;

use App\Entity\Category;
use App\Entity\Product;
use App\Entity\ProductConfiguration;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * @param string $url
     * @return Product[]
     */
    public function findByCategoryUrl($url)
    {
        return $this->createQueryBuilder("p")
            ->select("p,conf")
            ->leftJoin(Category::class, "cat", Join::WITH, "p.category = cat.id")
            ->leftJoin("p.configurations", "conf")
            ->where("cat.url = :url")
            ->setParameter(':url', $url)
            ->getQuery()
            ->getArrayResult();
    }

}
