<?php

namespace App\Repository;

use App\Entity\Category;
use App\Entity\Product;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ProductConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductConfigurationRepository extends EntityRepository
{
    /**
     * @param string $url
     * @return array
     */
    public function findByCategoryUrl($url)
    {
        return $this->createQueryBuilder("conf")
            ->select('conf')
            ->leftJoin(Product::class, "p", Join::WITH, "p.id = conf.product")
            ->leftJoin(Category::class, "cat", Join::WITH, "p.category = cat.id")
            ->where("cat.url = :url")
            ->groupBy("conf.value")
            ->setParameter("url", $url)
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
    }
}
